### ISSUE TITLE
Comparison with ABCore and few suggestions

### ISSUE THREAD

**Issue by ghost** [nayutaco/NayutaCore#1]
![Screenshot_20200901-020204__01](https://user-images.githubusercontent.com/13405205/91765927-63adb780-ebf7-11ea-8fad-6c485d9f7e02.jpg)

Things that look good: Recovery phrase, option to disable sync when using mobile data, pubkey and export logs

What's missing and is important: onion address, peers info, CONSOLE, size for pruning and bitcoin.conf link to edit manually

![Screenshot_20200901-015110__01](https://user-images.githubusercontent.com/13405205/91766422-2e559980-ebf8-11ea-9317-a14b7c4c188a.jpg)

I don't think other implementations of nodes are required right now and bitcoin core should work fine.

![Screenshot_20200901-015320__01](https://user-images.githubusercontent.com/13405205/91766445-39102e80-ebf8-11ea-8428-28f467f4af79.jpg)

I really need console option to try different commands and maybe few other users will need it as well if running full node on mobile phone.

![Screenshot_20200901-015742__01](https://user-images.githubusercontent.com/13405205/91766479-44fbf080-ebf8-11ea-9c3d-d0ee31eed060.jpg)

![Screenshot_20200901-015248__01](https://user-images.githubusercontent.com/13405205/91766517-504f1c00-ebf8-11ea-8eaf-b034bb986662.jpg)

The timeline data you added in Nayuta core looks amazing and maybe you can add this onion address in settings.

**Comment by mandelmonkey** [comment]
agree, there are plans to add more advanced features for power users in the settings
