### ISSUE TITLE
Missing Code for latest version on google-play 

### ISSUE THREAD

**Issue by emanuelb** [nayutaco/NayutaCore#3]
The app `com.nayuta.core` on google-play last updated in "April 12, 2021" https://play.google.com/store/apps/details?id=com.nayuta.core
While this repo latest commit is from: "Sep 1, 2020 " https://github.com/nayutaco/NayutaCore/commit/0d6e4caa7d9a93c1167409e3c17e95e9158c8d01

Please publish the source code for the latest app on google-play.

**Comment by mandelmonkey** [comment]
The current app is built from a new private repo, this is because the app has had a major refactor and is in testing on google play, once it is in a stable state it will be updated here or this repo will be closed an a new public one made

**Comment by emanuelb** [comment]
Any update regarding publishing the source code? the app on google-play last update is: "November 24, 2021" while latest commit is still from "Sep 1, 2020"

**Comment by mandelmonkey** [comment]
@nayuta-ueno is best to answer this question

**Comment by nueno4** [comment]
@emanuelb @mandelmonkey 

> Any update regarding publishing the source code? the app on google-play last update is: "November 24, 2021" while latest commit is still from "Sep 1, 2020"

Since there are still many experimental implementations, it is difficult to release the latest version code now.

**Comment by Giszmo** [comment]
> Since there are still many experimental implementations, it is difficult to release the latest version code now.

Curious comment. It wasn't difficult to release the binary. :disappointed:
